name: Deploy

on:
  push:
    branches:
      - forlive

jobs:
#  build_and_test:
#    name: Build and Test
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [16.x]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: npm ci, built and test
#        run: |
#          npm ci
#          npm run build
#          npm run test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    #needs: build_and_test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: pm2 stop
        run: ssh deploy 'pm2 stop extranet'
      - name: Fetch repo
        run: ssh deploy 'cd pp-extranet-svelte && git fetch && git reset --hard origin/forlive'
      - name: Npm install
        run: ssh deploy 'cd pp-extranet-svelte && npm install'
      - name: Npm run build
        run: ssh deploy 'cd pp-extranet-svelte && npm run build'
      - name: Npm run preview
        run: ssh deploy 'cd pp-extranet-svelte && pm2 start extranet'